name: hyper_effects_demo
description: A demo that showcases the hyper_effects package.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.4.1
  flutter_box_transform: ^0.4.2
  hyper_effects:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
