name: hyper_effects
description: Create beautiful effects and animations with just a few lines of code.

version: 0.0.1

homepage: https://hyperdesigned.dev/
repository: https://github.com/hyper-designed/hyper_effects
issue_tracker: https://github.com/hyper-designed/hyper_effects/issues
documentation: https://docs.page/hyper-designed/hyper_effects

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
