name: Deploy to Firebase Hosting on merge

on:
  push:
    paths:
      - '**.dart'
      - '**.yaml'
      - '**.yml'
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Flutter pub get
        run: flutter pub get
      - name: Build Example
        run: |
          cd example
          flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HYPER_EFFECTS_DEMO }}'
          channelId: live
          projectId: hyper-effects-demo
